version: '3.8'

services:

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/Quick_Food_Database
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Your_Password        # set your password
      - JWT_SECRET=Your_JWT_Secret_Key                  # set your jwt secret key

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=Quick_Food_Database
      - MYSQL_ROOT_PASSWORD=Your_Password           # set your password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
